### ISSUE TITLE
Mockery overload causes Fatal Error on Laravel 

### ISSUE THREAD

**Issue by akimkelar** [mockery/mockery#1119]
Mockery overload causes Fatal Error on Laravel in the case when the assertion does not pass.
Our team faced with this error many times and was unable even to understand what causes this behavior, because error message is not descriptive.
And now I have realised that it connected with Mockery and have successfully isolated this issue to provide you.

Tests are running on Laravel with Mockery
"name": "mockery/mockery",
"version": "1.4.2",
"name": "laravel/framework",
"version": "v6.20.13",
PHPUnit 8.5.14

The script is very simple:
this one is working
```
<?php

namespace Tests\Unit\App;

use App\Http\Services\GoogleMapsGeocode;
use Mockery;
use Tests\TestCase;

/**
 * Class MockeryTest
 * @package Tests\Unit\App
 * @runTestsInSeparateProcesses
 * @preserveGlobalState disabled
 */
class MockeryTest extends TestCase
{
    private $googleMaps;

    public function setUp(): void
    {
//        $this->googleMaps = Mockery::mock('overload:' . GoogleMapsGeocode::class)
//            ->makePartial();

        parent::setUp();
    }

    public function test_mockery()
    {
        $this->assertEquals([], [123]);
    }
}
```

and returns this result

```
bash-5.0# ./vendor/phpunit/phpunit/phpunit ./tests/Unit/App/MockeryTest.php 
PHPUnit 8.5.14 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 2.11 seconds, Memory: 10.00 MB

There was 1 failure:

1) Tests\Unit\App\MockeryTest::test_mockery
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
+    0 => 123
 )

/var/www/tests/Unit/App/MockeryTest.php:29

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
bash-5.0# 
```

And this one is not working and couses an error (instead of Google could be any class that should be overloaded)

```
<?php

namespace Tests\Unit\App;

use App\Http\Services\GoogleMapsGeocode;
use Mockery;
use Tests\TestCase;

/**
 * Class MockeryTest
 * @package Tests\Unit\App
 * @runTestsInSeparateProcesses
 * @preserveGlobalState disabled
 */
class MockeryTest extends TestCase
{
    private $googleMaps;

    public function setUp(): void
    {
        $this->googleMaps = Mockery::mock('overload:' . GoogleMapsGeocode::class)
            ->makePartial();

        parent::setUp();
    }

    public function test_mockery()
    {
        $this->assertEquals([], [123]);
    }
}
```

and it´s result

```
bash-5.0# ./vendor/phpunit/phpunit/phpunit ./tests/Unit/App/MockeryTest.php 
PHPUnit 8.5.14 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 1.29 seconds, Memory: 10.00 MB

There was 1 error:

1) Tests\Unit\App\MockeryTest::test_mockery
PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:978
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(812): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#5 /var/www/vendor/larave in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 978
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:978
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(812): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Contaibash-5.0# ./vendor/phpunit/phpunit/phpunit ./tests/Unit/App/MockeryTest.php 
PHPUnit 8.5.14 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 2.33 seconds, Memory: 10.00 MB

There was 1 error:

1) Tests\Unit\App\MockeryTest::test_mockery
PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:978
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(812): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#5 /var/www/vendor/larave in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 978
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:978
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(812): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#5 /var/www/vendor/larave in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 978

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
bash-5.0# 
```

**Comment by davedevelopment** [comment]
Honestly no idea on this one, hopefully someone else might be able to shed some light.
