### ISSUE TITLE
Mockery Expectations on Partial Mocks do not work as expected

### ISSUE THREAD

**Issue by kwhat** [mockery/mockery#586]
Best I can tell from the docs, the following should constrain the number of calls to getBody to AT LEAST 152345 times.  This test always passes.  It doesn't matter if I call getBody and specify never() or call it 30x with once(), it always passes and does return "YourMom" without much trouble.  Please fix this library or spend 5 minutes outlining this special _"short-bus"_ case in the partial mocks section of the docs.  P.S. Why does that section of the docs refer back to the Quick start guide and not the other way around?

```
    $mockEnv = Slim\Environment::mock(array(
        "REQUEST_METHOD" => "POST",
        "slim.input" => json_encode(array("key" => "value"))
    ));
   $mockRequest = Mockery::mock("Slim\\Http\\Request[getBody]", array($mockEnv));
   $mockRequest->shouldReceive("getBody")->andReturn("YourMom")->atLeast(152345);
   $mockRequest->getBody();
```

**Comment by davedevelopment** [comment]
Try this:

``` php
$mockRequest->shouldReceive("getBody")->andReturn("YourMom")->atLeast()->times(152345); 
```

**Comment by kwhat** [comment]
Continues passing.

**Comment by davedevelopment** [comment]
Are you calling `Mockery::close()`?

``` php
<?php

use Mockery as m;

require "vendor/autoload.php";

Mockery::setLoader(new Mockery\Loader\RequireLoader(__DIR__));
error_reporting(E_ALL);

class Foo {
    function __construct() {}
    function getBody() {}
}

$mockRequest = Mockery::mock("Foo[getBody]", array(new stdClass()));
$mockRequest->shouldReceive("getBody")->andReturn("YourMom")->atLeast()->times(152345);
$mockRequest->getBody();

Mockery::close();
/*
PHP Fatal error:  Uncaught Mockery\Exception\InvalidCountException: Method getBody() from Mockery_0_Foo should be called
 at least 152345 times but called 1 times. in /home/davem/src/mockery/library/Mockery/CountValidator/AtLeast.php:47
Stack trace:
#0 /home/davem/src/mockery/library/Mockery/Expectation.php(275): Mockery\CountValidator\AtLeast->validate(1)
#1 /home/davem/src/mockery/library/Mockery/ExpectationDirector.php(119): Mockery\Expectation->verify()
#2 /home/davem/src/mockery/MockeryYyfXRN(375): Mockery\ExpectationDirector->verify()
#3 /home/davem/src/mockery/library/Mockery/Container.php(309): Mockery_0_Foo->mockery_verify()
#4 /home/davem/src/mockery/library/Mockery/Container.php(294): Mockery\Container->mockery_verify()
#5 /home/davem/src/mockery/library/Mockery.php(158): Mockery\Container->mockery_teardown()
#6 /home/davem/src/mockery/test.php(19): Mockery::close()
#7 {main}
  thrown in /home/davem/src/mockery/library/Mockery/CountValidator/AtLeast.php on line 47


*/
```

**Comment by robertbasic** [comment]
@davedevelopment I believe this issue can be closed.

**Comment by robertbasic** [comment]
Closing as @davedevelopment's comment suggest all is working as expected.

Please reopen if this is still an issue for you.
