### ISSUE TITLE
Mockery won't throw errors

### ISSUE THREAD

**Issue by Bilge** [mockery/mockery#767]
```php
// Ask Mockery to throw an error:
$foo = \Mockery::mock(Foo::class)
    ->shouldReceive('bar')
    ->andThrow(\Error::class)
    ->once()
    ->getMock(),

// It doesn't bother.
$foo->bar(); 
```

If `Error::class` is substituted for `Exception::class`, this works as expected, but Mockery won't throw `Error`s.

**Comment by robertbasic** [comment]
This has been possible since January with https://github.com/mockery/mockery/pull/679

I ran locally the case you provided, and this is the result:

```
robert@odin ~/projects/mockery[master*]$ php adhoc-tests/issue767.php 
PHP Fatal error:  Uncaught Error in /home/robert/projects/mockery/library/Mockery/Expectation.php:562
Stack trace:
#0 [internal function]: Mockery\Expectation->andThrow('Error')
#1 /home/robert/projects/mockery/library/Mockery/CompositeExpectation.php(72): call_user_func_array(Array, Array)
#2 /home/robert/projects/mockery/adhoc-tests/issue767.php(8): Mockery\CompositeExpectation->__call('andThrow', Array)
#3 {main}
  thrown in /home/robert/projects/mockery/library/Mockery/Expectation.php on line 562
```

Closing as not an issue.
