### ISSUE TITLE
Exception: At least 3 baseline test run memory profiles are required, 2 given in roave/no-leaks/src/MeasuredBaselineTestMemoryLeak.php:70

### ISSUE THREAD

**Issue by petrhejna** [mockery/mockery#961]
Hi, I have encountered this issue and I have no idea what does it means.

Doing `var_dump($nonNegativeMemoryUsages);` in `MeasuredBaselineTestMemoryLeak.php:70`

result: 
```php
array(1) {
  [0] =>
  int(32)
}
```

Full error dump:
```
Exception: At least 3 baseline test run memory profiles are required, 2 given in /var/www/html/vendor/roave/no-leaks/src/MeasuredBaselineTestMemoryLeak.php:70
Stack trace:
#0 /var/www/html/vendor/roave/no-leaks/src/CollectTestExecutionMemoryFootprints.php(76): Roave\NoLeaks\PHPUnit\MeasuredBaselineTestMemoryLeak::fromBaselineTestMemoryUsages(Array, Array)
#1 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(599): Roave\NoLeaks\PHPUnit\CollectTestExecutionMemoryFootprints->executeAfterLastTest()
#2 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(208): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#3 /var/www/html/vendor/roave/no-leaks/bin/roave-no-leaks.php(46): PHPUnit\TextUI\Command->run(Array, true)
#4 /var/www/html/vendor/roave/no-leaks/bin/roave-no-leaks.php(47): Roave\NoLeaks\CLI\{closure}()
#5 /var/www/html/vendor/roave/no-leaks/bin/roave-no-leaks(9): require('/var/www/html/v...')
#6 /var/www/html/vendor/roave/no-leaks/bin/roave-no-leaks(10): Roave\NoLeaks\CLI\{closure}()
#7 {main}
```

Can you please provide any hint what this means and how to solve this? If you need additional info, just tell me what to look for.

Thanks a lot. :)

**Comment by robertbasic** [comment]
Hi!

I believe this is for a different project? https://github.com/roave/no-leaks

Closing as it has nothing to do with Mockery.

Have a nice day!

**Comment by petrhejna** [comment]
Ah, thanks a a lot :) my mistake - I had multiple tabs opened and put it in a wrong one. Sorry :pray:
